export interface StateCities {
  state: string
  cities: string[]
}

export const INDIA_STATES_AND_CITIES: StateCities[] = [
  {
    state: 'Andhra Pradesh',
    cities: [
      'Visakhapatnam',
      'Vijayawada',
      'Guntur',
      'Nellore',
      'Kurnool',
      'Kakinada',
      'Rajahmundry',
      'Kadapa',
      'Tirupati',
      'Anantapur',
      'Eluru',
      'Vizianagaram',
      'Ongole',
      'Nandyal',
      'Machilipatnam',
      'Adoni',
      'Tenali',
      'Chittoor',
      'Hindupur',
      'Proddatur',
      'Bhimavaram',
      'Madanapalle',
      'Guntakal',
      'Dharmavaram',
      'Gudivada',
      'Srikakulam',
    ],
  },
  {
    state: 'Arunachal Pradesh',
    cities: [
      'Itanagar',
      'Naharlagun',
      'Pasighat',
      'Namsai',
      'Tawang',
      'Ziro',
      'Aalo',
      'Tezu',
      'Bomdila',
      'Khonsa',
      'Roing',
    ],
  },
  {
    state: 'Assam',
    cities: [
      'Guwahati',
      'Silchar',
      'Dibrugarh',
      'Jorhat',
      'Nagaon',
      'Tinsukia',
      'Tezpur',
      'Bongaigaon',
      'Karimganj',
      'Sivasagar',
      'North Lakhimpur',
      'Dhubri',
      'Barpeta',
      'Goalpara',
      'Diphu',
    ],
  },
  {
    state: 'Bihar',
    cities: [
      'Patna',
      'Gaya',
      'Bhagalpur',
      'Muzaffarpur',
      'Purnia',
      'Darbhanga',
      'Bihar Sharif',
      'Arrah',
      'Begusarai',
      'Katihar',
      'Munger',
      'Chhapra',
      'Bettiah',
      'Saharsa',
      'Sasaram',
      'Hajipur',
      'Dehri',
      'Siwan',
      'Motihari',
      'Buxar',
      'Kishanganj',
      'Lakhisarai',
      'Jamui',
      'Sitamarhi',
      'Jehanabad',
      'Aurangabad',
    ],
  },
  {
    state: 'Chhattisgarh',
    cities: [
      'Raipur',
      'Bhilai',
      'Bilaspur',
      'Korba',
      'Rajnandgaon',
      'Raigarh',
      'Jagdalpur',
      'Ambikapur',
      'Dhamtari',
      'Durg',
      'Mahasamund',
      'Champa',
      'Bhatapara',
      'Kanker',
      'Kondagaon',
    ],
  },
  {
    state: 'Delhi',
    cities: [
      'New Delhi',
      'Delhi',
      'Dwarka',
      'Rohini',
      'Narela',
      'Najafgarh',
      'Vasant Kunj',
      'Mayur Vihar',
      'Karol Bagh',
      'Connaught Place',
    ],
  },
  {
    state: 'Goa',
    cities: [
      'Panaji',
      'Margao',
      'Vasco da Gama',
      'Mapusa',
      'Ponda',
      'Bicholim',
      'Curchorem',
      'Valpoi',
      'Pernem',
    ],
  },
  {
    state: 'Gujarat',
    cities: [
      'Ahmedabad',
      'Surat',
      'Vadodara',
      'Rajkot',
      'Bhavnagar',
      'Jamnagar',
      'Junagadh',
      'Gandhinagar',
      'Nadiad',
      'Gandhidham',
      'Anand',
      'Morbi',
      'Surendranagar',
      'Bharuch',
      'Navsari',
      'Valsad',
      'Vapi',
      'Bhuj',
      'Patan',
      'Kalol',
      'Botad',
      'Amreli',
    ],
  },
  {
    state: 'Haryana',
    cities: [
      'Faridabad',
      'Gurugram',
      'Panipat',
      'Ambala',
      'Yamunanagar',
      'Rohtak',
      'Hisar',
      'Karnal',
      'Sonipat',
      'Panchkula',
      'Sirsa',
      'Bahadurgarh',
      'Jind',
      'Thanesar',
      'Kaithal',
      'Rewari',
      'Palwal',
    ],
  },
  {
    state: 'Himachal Pradesh',
    cities: [
      'Shimla',
      'Dharamshala',
      'Solan',
      'Mandi',
      'Nahan',
      'Una',
      'Hamirpur',
      'Bilaspur',
      'Kullu',
      'Chamba',
      'Paonta Sahib',
      'Baddi',
    ],
  },
  {
    state: 'Jammu and Kashmir',
    cities: [
      'Srinagar',
      'Jammu',
      'Anantnag',
      'Baramulla',
      'Kathua',
      'Sopore',
      'Samba',
      'Udhampur',
      'Poonch',
      'Rajouri',
      'Kupwara',
    ],
  },
  {
    state: 'Jharkhand',
    cities: [
      'Ranchi',
      'Jamshedpur',
      'Dhanbad',
      'Bokaro Steel City',
      'Deoghar',
      'Hazaribagh',
      'Giridih',
      'Ramgarh',
      'Phusro',
      'Medininagar',
      'Chas',
      'Adityapur',
      'Dumka',
      'Sahibganj',
      'Jhumri Telaiya',
    ],
  },
  {
    state: 'Karnataka',
    cities: [
      'Bengaluru',
      'Hubballi-Dharwad',
      'Mysuru',
      'Kalaburagi',
      'Mangaluru',
      'Belagavi',
      'Davanagere',
      'Ballari',
      'Vijayapura',
      'Shivamogga',
      'Tumakuru',
      'Raichur',
      'Bidar',
      'Hosapete',
      'Hassan',
      'Gadag-Betageri',
      'Udupi',
      'Bhadravati',
      'Robertsonpet',
      'Chitradurga',
      'Kolar',
      'Mandya',
      'Chikkamagaluru',
      'Bagalkot',
      'Ranibennur',
    ],
  },
  {
    state: 'Kerala',
    cities: [
      'Thiruvananthapuram',
      'Kochi',
      'Kozhikode',
      'Kollam',
      'Thrissur',
      'Kannur',
      'Alappuzha',
      'Palakkad',
      'Kottayam',
      'Manjeri',
      'Thalassery',
      'Ponnani',
      'Vatakara',
      'Kanhangad',
      'Kasaragod',
    ],
  },
  {
    state: 'Ladakh',
    cities: ['Leh', 'Kargil'],
  },
  {
    state: 'Madhya Pradesh',
    cities: [
      'Indore',
      'Bhopal',
      'Jabalpur',
      'Gwalior',
      'Ujjain',
      'Sagar',
      'Dewas',
      'Satna',
      'Ratlam',
      'Rewa',
      'Murwara',
      'Singrauli',
      'Burhanpur',
      'Khandwa',
      'Morena',
      'Bhind',
      'Chhindwara',
      'Guna',
      'Shivpuri',
      'Vidisha',
      'Damoh',
      'Mandsaur',
      'Khargone',
    ],
  },
  {
    state: 'Maharashtra',
    cities: [
      'Mumbai',
      'Pune',
      'Nagpur',
      'Thane',
      'Pimpri-Chinchwad',
      'Nashik',
      'Kalyan-Dombivli',
      'Vasai-Virar',
      'Aurangabad',
      'Navi Mumbai',
      'Solapur',
      'Mira-Bhayandar',
      'Bhiwandi',
      'Amravati',
      'Nanded',
      'Kolhapur',
      'Akola',
      'Ulhasnagar',
      'Sangli',
      'Jalgaon',
      'Dhule',
      'Ahmednagar',
      'Chandrapur',
      'Parbhani',
      'Ichalkaranji',
      'Jalna',
      'Latur',
      'Satara',
    ],
  },
  {
    state: 'Manipur',
    cities: [
      'Imphal',
      'Thoubal',
      'Kakching',
      'Mayang Imphal',
      'Ukhrul',
      'Churachandpur',
      'Senapati',
    ],
  },
  {
    state: 'Meghalaya',
    cities: ['Shillong', 'Tura', 'Jowai', 'Nongstoin', 'Williamnagar'],
  },
  {
    state: 'Mizoram',
    cities: ['Aizawl', 'Lunglei', 'Saiha', 'Champhai', 'Kolasib'],
  },
  {
    state: 'Nagaland',
    cities: ['Dimapur', 'Kohima', 'Mokokchung', 'Tuensang', 'Wokha', 'Zunheboto', 'Phek'],
  },
  {
    state: 'Odisha',
    cities: [
      'Bhubaneswar',
      'Cuttack',
      'Rourkela',
      'Brahmapur',
      'Sambalpur',
      'Puri',
      'Balasore',
      'Bhadrak',
      'Baripada',
      'Jharsuguda',
      'Balangir',
      'Paradip',
      'Rayagada',
      'Koraput',
      'Jeypore',
    ],
  },
  {
    state: 'Punjab',
    cities: [
      'Ludhiana',
      'Amritsar',
      'Jalandhar',
      'Patiala',
      'Bathinda',
      'Mohali',
      'Hoshiarpur',
      'Pathankot',
      'Moga',
      'Abohar',
      'Khanna',
      'Phagwara',
      'Muktsar',
      'Barnala',
      'Firozpur',
    ],
  },
  {
    state: 'Rajasthan',
    cities: [
      'Jaipur',
      'Jodhpur',
      'Kota',
      'Bikaner',
      'Ajmer',
      'Udaipur',
      'Bhilwara',
      'Alwar',
      'Sikar',
      'Bharatpur',
      'Sri Ganganagar',
      'Pali',
      'Chittorgarh',
      'Jaisalmer',
      'Barmer',
      'Hanumangarh',
      'Tonk',
      'Beawar',
      'Kishangarh',
      'Hindaun',
      'Gangapur City',
    ],
  },
  {
    state: 'Sikkim',
    cities: ['Gangtok', 'Namchi', 'Geyzing', 'Mangan'],
  },
  {
    state: 'Tamil Nadu',
    cities: [
      'Chennai',
      'Coimbatore',
      'Madurai',
      'Tiruchirappalli',
      'Salem',
      'Tiruppur',
      'Erode',
      'Vellore',
      'Thoothukudi',
      'Tirunelveli',
      'Nagercoil',
      'Thanjavur',
      'Dindigul',
      'Karur',
      'Ranipet',
      'Sivakasi',
      'Kancheepuram',
      'Ooty',
      'Pollachi',
      'Karaikudi',
    ],
  },
  {
    state: 'Telangana',
    cities: [
      'Hyderabad',
      'Warangal',
      'Nizamabad',
      'Khammam',
      'Karimnagar',
      'Ramagundam',
      'Mahbubnagar',
      'Nalgonda',
      'Adilabad',
      'Suryapet',
      'Miryalaguda',
      'Siddipet',
      'Jagtial',
      'Mancherial',
    ],
  },
  {
    state: 'Tripura',
    cities: ['Agartala', 'Dharmanagar', 'Udaipur', 'Kailasahar', 'Belonia'],
  },
  {
    state: 'Uttar Pradesh',
    cities: [
      'Lucknow',
      'Kanpur',
      'Ghaziabad',
      'Agra',
      'Meerut',
      'Varanasi',
      'Prayagraj',
      'Bareilly',
      'Aligarh',
      'Moradabad',
      'Saharanpur',
      'Gorakhpur',
      'Noida',
      'Firozabad',
      'Jhansi',
      'Muzaffarnagar',
      'Mathura',
      'Ayodhya',
      'Rampur',
      'Shahjahanpur',
      'Farrukhabad',
      'Hapur',
      'Mau',
      'Mirzapur',
      'Bulandshahr',
      'Etawah',
    ],
  },
  {
    state: 'Uttarakhand',
    cities: [
      'Dehradun',
      'Haridwar',
      'Roorkee',
      'Haldwani',
      'Rudrapur',
      'Kashipur',
      'Rishikesh',
      'Pithoragarh',
      'Ramnagar',
    ],
  },
  {
    state: 'West Bengal',
    cities: [
      'Kolkata',
      'Howrah',
      'Darjeeling',
      'Siliguri',
      'Asansol',
      'Durgapur',
      'Bardhaman',
      'Malda',
      'Baharampur',
      'Jalpaiguri',
      'Kharagpur',
      'Haldia',
      'Balurghat',
      'Purulia',
      'Raniganj',
    ],
  },
  {
    state: 'Andaman and Nicobar Islands',
    cities: ['Port Blair'],
  },
  {
    state: 'Chandigarh',
    cities: ['Chandigarh'],
  },
  {
    state: 'Dadra and Nagar Haveli and Daman and Diu',
    cities: ['Daman', 'Diu', 'Silvassa'],
  },
  {
    state: 'Lakshadweep',
    cities: ['Kavaratti'],
  },
  {
    state: 'Puducherry',
    cities: ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
  },
]

export const INDIA_STATES = INDIA_STATES_AND_CITIES.map((item) => item.state).sort()

export function getCitiesByState(stateName: string): string[] {
  const item = INDIA_STATES_AND_CITIES.find(
    (s) => s.state.toLowerCase() === stateName.toLowerCase()
  )
  return item ? item.cities.sort() : []
}
